---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept  
#  product_name: chef
#  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
#  install_strategy: once
  retry_on_exit_code:
    - 0
    - 1 # Exit, success: You still must reboot, this just notes that the automatic restart flag was removed
    - 2 # Exit, success, need to reboot
    - 3 # Exit, success, with a non-critical failure: Typically seen when returning the DNS Delegation warning.
    - 4 # Exit, success, with a non-critical failure, need to reboot: Typically seen when returning the DNS Delegation warning.
    - 35 # 35 is the exit code signaling that the node is rebooting
    - 1190 #1190 is the exit code signaling that a reboot is scheduled
  wait_for_retry: 200 # May need to increase depending on computing resources.
  max_retries: 1

verifier:
  name: inspec

#transport:
#  name: winrm
#  elevated: true  # Required to get Windows Update to run
#  winrm_transport: plaintext  # When set to plaintext the winrm will run in one converge

platforms:
  - name: windows-2008-r2
    driver:
      box: tas50/windows_2008r2
  - name: windows-2012-r2
    driver:
      box: tas50/windows_2012r2
      customize:
        memory: 2048
  - name: windows-2016
    driver:
      box: tas50/windows_2016
      customize:
        memory: 2048
  - name: windows-2019
    driver:
      box: tas50/windows_2019
      customize:
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[windows_ad::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

  - name: forest
    run_list:
      - recipe[windows_ad_test::setup_forest]
    verifier:
      inspec_tests:
        - test/integration/forest
    attributes:
