# cookstyle todo

Lint/ElseLayout:
  Exclude:
    - 'providers/domain.rb'

Lint/EndAlignment:
  Exclude:
    - 'providers/computer.rb'
    - 'providers/domain.rb'

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/fixtures/test_cookbooks/test_windows_ad/recipes/setup_forest.rb'

Lint/UselessAssignment:
  Exclude:
    - 'Vagrantfile'
    - 'test/fixtures/test_cookbooks/test_windows_ad/recipes/group.rb'
    - 'test/fixtures/test_cookbooks/test_windows_ad/recipes/ou.rb'
    - 'test/fixtures/test_cookbooks/test_windows_ad/recipes/user.rb'

Lint/Void:
  Exclude:
    - 'providers/domain.rb'

Metrics/BlockNesting:
  Max: 4

Style/IdenticalConditionalBranches:
  Exclude:
    - 'providers/user.rb'

Style/IfInsideElse:
  Exclude:
    - 'providers/domain.rb'
