inherit_from: .rubocop_todo.yml

Metrics/BlockNesting:
  Max: 4

Metrics/LineLength:
  Max: 180

Layout/EndOfLine:
  EnforcedStyle: lf

Style/IfInsideElse:
  Exclude:
    - 'resources/domain.rb'
