name             'windows_ad'
maintainer       'Texas A&M'
maintainer_email 'derekgroh@github.com'
license          'MIT'
description      'Installs/Configures windows active directory'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.6.2'
issues_url       'https://github.com/TAMUArch/cookbook.windows_ad/issues'
source_url       'https://github.com/TAMUArch/cookbook.windows_ad'
supports         'windows', '>= 6.1'
depends          'windows', '~> 3.1.1'
chef_version     '>= 12.1'
