name             'windows_ad'
maintainer       'Texas A&M'
maintainer_email 'derekgroh@github.com'
license          'MIT'
description      'Installs/Configures windows active directory'
version          '0.6.4'
issues_url       'https://github.com/TAMUArch/cookbook.windows_ad/issues'
source_url       'https://github.com/TAMUArch/cookbook.windows_ad'
supports         'windows', '>= 6.1'
depends          'windows'
chef_version     '>= 12.1'
